### ISSUE TITLE
Map API - research

### ISSUE THREAD

**Issue by carflor** [StreetArtMap/streetArtMap#8]
- [ ] figure out which map API will be best for the scope of our application 

- Google API
- MapQuest API
**- Mapbox** 

- [ ] should we use a street art API that might contain location / artist / etc for a starting database for our app or should we start from scratch documenting different artworks

**Comment by stellakunzang** [comment]
@carflor We checked out the limits for each pertaining to how many stops can be added to a route and MapQuest was the winner with 50, followed by Mapbox with 25. Mapbox seems to have cooler display though, so I'd say the ball is in your (FE) court.

**Comment by stellakunzang** [comment]
re Street Art API: The ones I found didn't seem to be very relevant to what we are doing or usable. Would you please link any you find so we can asses in terms of database if they will be helpful or create more of a headache?
